import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full p-2 underline text-blue-500 text-xl flex justify-center gap-2 flex-wrap">
          <Link href="/">Home</Link>
          <Link href="/use-transition">useTransition</Link>
          <Link href="/use-action-state">useActionState</Link>
          <Link href="/ui-blocking">UI Blocking</Link>
          <Link href="/none-ui-blocking">None UI Blocking</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
